<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Modula-3</string>
  <key>fileTypes</key>
  <array>
    <string>m3</string>
    <string>mg</string>
    <string>i3</string>
    <string>ig</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>name</key>
      <string>keyword.modula-3</string>
      <key>match</key>
      <string>\b(AND|ANY|ARRAY|AS|BEGIN|BITS|BRANDED|BY|CASE|CONST|DIV|DO|ELSE|ELSIF|END|EVAL|EXCEPT|EXCEPTION|EXIT|EXPORTS|FINALLY|FOR|FROM|GENERIC|IF|IMPORT|IN|INTERFACE|LOCK|LOOP|METHODS|MOD|MODULE|NOT|OBJECT|OF|OR|OVERRIDES|PROCEDURE|RAISE|RAISES|READONLY|RECORD|REF|REPEAT|RETURN|REVEAL|SET|THEN|TO|TRY|TYPE|TYPECASE|UNSAFE|UNTIL|UNTRACED|VALUE|VAR|WHILE|WITH)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.modula-3</string>
      <key>match</key>
      <string>\b(ABS|ADDRESS|ADR|ADRSIZE|ANY|BITSIZE|BOOLEAN|BYTESIZE|CARDINAL|CEILING|CHAR|DEC|DISPOSE|EXTENDED|FALSE|FIRST|FLOAT|FLOOR|INC|INTEGER|ISTYPE|LAST|LONGREAL|LOOPHOLE|MAX|MIN|MUTEX|NARROW|NEW|NIL|NULL|NUMBER|ORD|REAL|REFANY|ROOT|ROUND|SUBARRAY|TEXT|TRUE|TRUNC|TYPECODE|VAL)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.modula-3._cm3</string>
      <key>match</key>
      <string>\b(LONGCARD|LONGINT)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.float.modula-3</string>
      <key>match</key>
      <string>\b[0-9]+\.[0-9]+([DdEeXx][\+\-]?[0-9]+)?\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.integer.modula-3</string>
      <key>match</key>
      <string>\b[0-9]+(\_[0-9a-fA-F]+)?L?\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.double.modula-3</string>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#escape_sequence</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.single.modula-3</string>
      <key>begin</key>
      <string>'</string>
      <key>end</key>
      <string>'</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#escape_sequence</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.control.assert.modula-3._cm3</string>
      <key>begin</key>
      <string>&lt;\*\s*ASSERT\b</string>
      <key>end</key>
      <string>\*&gt;</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#pragma</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.control.debug.modula-3._cm3</string>
      <key>begin</key>
      <string>&lt;\*\s*DEBUG\b</string>
      <key>end</key>
      <string>\*&gt;</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#pragma</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#pragma</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>escape_sequence</key>
    <dict>
      <key>name</key>
      <string>constant.character.escape.modula-3</string>
      <key>match</key>
      <string>\\[0-7]{3}|\\[\\fnrt\"\']</string>
    </dict>
    <key>comment</key>
    <dict>
      <key>name</key>
      <string>comment.block.modula-3</string>
      <key>begin</key>
      <string>\(\*</string>
      <key>end</key>
      <string>\*\)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
      </array>
    </dict>
    <key>pragma</key>
    <dict>
      <key>name</key>
      <string>keyword.control.directive.pragma.modula-3</string>
      <key>begin</key>
      <string>\&lt;\*</string>
      <key>end</key>
      <string>\*\&gt;</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#pragma</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.modula-3</string>
  <key>uuid</key>
  <string>4c94bed0-63b5-43a2-b2be-d777f02a0a95</string>
</dict>
</plist>
