<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Quake</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>name</key>
      <string>keyword.quake</string>
      <key>match</key>
      <string>\b(and|contains|else|end|for|foreach|if|in|is|local|not|or|proc|readonly|return)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.integer.quake</string>
      <key>match</key>
      <string>\b[0-9]+\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>comment.line.percentage.quake</string>
      <key>match</key>
      <string>%.*$</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#block_comment</string>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.double.quake</string>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.character.escape.quake</string>
          <key>match</key>
          <string>\\[0-7]{3}|\\[\\fnrt\"\']</string>
        </dict>
      </array>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>block_comment</key>
    <dict>
      <key>name</key>
      <string>comment.block.quake</string>
      <key>begin</key>
      <string>\/\*</string>
      <key>end</key>
      <string>\*\/</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#block_comment</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.quake</string>
  <key>uuid</key>
  <string>987a861a-6572-45f3-8b43-fade130ff882</string>
</dict>
</plist>
